# Generated by Django 3.1.1 on 2020-12-28 17:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название, отображаемое в админке')),
                ('start_message', models.TextField(verbose_name='Вступительное сообщение')),
                ('end_message', models.TextField(verbose_name='Заключительное сообщение')),
                ('token', models.CharField(help_text='<span style="color:red;font-weight:bold;">ВНИМАНИЕ: редактирование этого поля может сломать Вашего бота.</a>\n Получить токен для нового бота телеграм <br />можно с использованием <a href="https://t.me/BotFather">https://t.me/BotFather</a>', max_length=64, unique=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.CreateModel(
            name='ChatNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=550, null=True, verbose_name='Ответ')),
                ('question', models.CharField(max_length=550, verbose_name='Вопрос')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chattree.chatnode', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя телеграм')),
                ('chat_id', models.PositiveIntegerField(verbose_name='ID чата телеграм')),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('message_id', models.PositiveIntegerField(verbose_name='ID сообщения телеграм')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя телеграм')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия (Last name)')),
                ('language_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='IETF_language_tag')),
                ('message_date', models.DateTimeField()),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattree.bot', verbose_name='Бот')),
                ('chat_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattree.chatnode', verbose_name='Вопрос, который задан пользователю')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='chat_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattree.chatnode', verbose_name='Ветка вопросов и ответов'),
        ),
    ]
