# Generated by Django 3.1.1 on 2020-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
