# Generated by Django 3.1.1 on 2020-09-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0003_auto_20200903_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalChatNode',
        ),
    ]
