# Generated by Django 3.1.1 on 2020-09-05 12:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0005_historicalchatnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatnode',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chattree.chatnode', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='HistoricalChatNode',
        ),
    ]
