# Generated by Django 3.1.1 on 2020-09-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0006_auto_20200905_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='Токен')),
                ('name', models.CharField(max_length=120, verbose_name='Название, отображаемое в админке')),
                ('start_message', models.TextField(verbose_name='Вступительное сообщение')),
                ('end_message', models.TextField(verbose_name='Заключительное сообщение')),
                ('chat_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chattree.chatnode', verbose_name='Ветка вопросов и ответов')),
            ],
        ),
    ]
