# Generated by Django 3.1.1 on 2020-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0007_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(help_text='<span style="color:red;font-weight:bold;">ВНИМАНИЕ: редактирование этого поля может сломать Вашего бота.</a>\n Получить токен для нового бота телеграм <br />можно с использованием <a href="https://t.me/BotFather">https://t.me/BotFather</a>', max_length=64, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='answer',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='chatnode',
            name='question',
            field=models.CharField(max_length=550, verbose_name='Вопрос'),
        ),
    ]
