# Generated by Django 3.1.1 on 2020-11-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattree', '0009_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatnode',
            name='question',
            field=models.CharField(max_length=4096, verbose_name='Вопрос'),
        ),
    ]
